.PHONY: clean All

All:
	@echo "----------Building project:[ DiagonalMatrix - Debug ]----------"
	@cd "DiagonalMatrix" && "$(MAKE)" -f  "DiagonalMatrix.mk"
clean:
	@echo "----------Cleaning project:[ DiagonalMatrix - Debug ]----------"
	@cd "DiagonalMatrix" && "$(MAKE)" -f  "DiagonalMatrix.mk" clean
