.PHONY: clean All

All:
	@echo "----------Building project:[ DoublyLinkedList - Debug ]----------"
	@cd "DoublyLinkedList" && "$(MAKE)" -f  "DoublyLinkedList.mk"
clean:
	@echo "----------Cleaning project:[ DoublyLinkedList - Debug ]----------"
	@cd "DoublyLinkedList" && "$(MAKE)" -f  "DoublyLinkedList.mk" clean
