.PHONY: clean All

All:
	@echo "----------Building project:[ Stack_LinkedList - Debug ]----------"
	@cd "Stack_LinkedList" && "$(MAKE)" -f  "Stack_LinkedList.mk"
clean:
	@echo "----------Cleaning project:[ Stack_LinkedList - Debug ]----------"
	@cd "Stack_LinkedList" && "$(MAKE)" -f  "Stack_LinkedList.mk" clean
