.PHONY: clean All

All:
	@echo "----------Building project:[ FibonacciSeries - Debug ]----------"
	@cd "FibonacciSeries" && "$(MAKE)" -f  "FibonacciSeries.mk"
clean:
	@echo "----------Cleaning project:[ FibonacciSeries - Debug ]----------"
	@cd "FibonacciSeries" && "$(MAKE)" -f  "FibonacciSeries.mk" clean
