.PHONY: clean All

All:
	@echo "----------Building project:[ GeneratePermutationsSwapping - Debug ]----------"
	@cd "GeneratePermutationsSwapping" && "$(MAKE)" -f  "GeneratePermutationsSwapping.mk"
clean:
	@echo "----------Cleaning project:[ GeneratePermutationsSwapping - Debug ]----------"
	@cd "GeneratePermutationsSwapping" && "$(MAKE)" -f  "GeneratePermutationsSwapping.mk" clean
