.PHONY: clean All

All:
	@echo "----------Building project:[ Queue_LinkedList - Debug ]----------"
	@cd "Queue_LinkedList" && "$(MAKE)" -f  "Queue_LinkedList.mk"
clean:
	@echo "----------Cleaning project:[ Queue_LinkedList - Debug ]----------"
	@cd "Queue_LinkedList" && "$(MAKE)" -f  "Queue_LinkedList.mk" clean
