.PHONY: clean All

All:
	@echo "----------Building project:[ TemplateClasses - Debug ]----------"
	@cd "TemplateClasses" && "$(MAKE)" -f  "TemplateClasses.mk"
clean:
	@echo "----------Cleaning project:[ TemplateClasses - Debug ]----------"
	@cd "TemplateClasses" && "$(MAKE)" -f  "TemplateClasses.mk" clean
