.PHONY: clean All

All:
	@echo "----------Building project:[ FindingSingleMissingElement - Debug ]----------"
	@cd "FindingSingleMissingElement" && "$(MAKE)" -f  "FindingSingleMissingElement.mk"
clean:
	@echo "----------Cleaning project:[ FindingSingleMissingElement - Debug ]----------"
	@cd "FindingSingleMissingElement" && "$(MAKE)" -f  "FindingSingleMissingElement.mk" clean
